src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: EvenementRepository::class)]
class Evenement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'evenements')]

    #[ORM\JoinColumn(name: 'id_club', referencedColumnName: 'id')]
    #[Assert\NotBlank]
    private ?Club $id_club;

    #[ORM\Column(type: "string", length: 255, nullable: false, name: 'titre')]
    #[Assert\NotBlank(message: 'The title is required.')]
    private ?string $titre;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'The description is required.')]
    private ?string $description;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Lieu is required.')]
    private ?string $lieu;

    #[ORM\Column(type: Types::DATE_MUTABLE, name: 'date_debut')]
    #[Assert\NotBlank]
    #[Assert\DateTimeInterface]
    private ?\DateTimeInterface $date_debut;

    #[ORM\Column(type: Types::DATE_MUTABLE, name: 'date_fin')]
    #[Assert\NotBlank]
    #[Assert\Expression(
        "(this.getDateFin() >= this.getDateDebut())",
        message: "La date de fin doit être postérieure à la date de début"
    )]
    #[Assert\DateTimeInterface]
    private ?\DateTimeInterface $date_fin;

    #[ORM\OneToMany(targetEntity: ParticipationEvenement::class, mappedBy: 'id_evenement')]
    private Collection $participationEvenements;

    public function __construct()
    {
        $this->participationEvenements = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdClub(): ?Club
    {
        return $this->id_club;
    }

    public function setIdClub(?Club $id_club): static
    {
        $this->id_club = $id_club;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): static
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection<int, ParticipationEvenement>
     */
    public function getParticipationEvenements(): Collection
    {
        return $this->participationEvenements;
    }

    public function addParticipationEvenement(ParticipationEvenement $participationEvenement): static
    {
        if (!$this->participationEvenements->contains($participationEvenement)) {
            $this->participationEvenements->add($participationEvenement);
            $participationEvenement->setIdEvenement($this);
        }

        return $this;
    }

    public function removeParticipationEvenement(ParticipationEvenement $participationEvenement): static
    {
        if ($this->participationEvenements->removeElement($participationEvenement)) {
            // set the owning side to null (unless already changed)
            if ($participationEvenement->getIdEvenement() === $this) {
                $participationEvenement->setIdEvenement(null);
            }
        }

        return $this;
    }
}

src/Form/ClubType.php
<?php

namespace App\Form;

use App\Entity\Club;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;



class ClubType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('intitule', TextType::class)
            ->add('logo', FileType::class, [
                'data_class' => null, // Indiquer que le champ n'est lié à aucune propriété de l'entité
                'data' => $options['current_logo_path'], // Définir l'URL actuelle de l'image comme valeur par défaut,
                'required' => false,
            ])
            ->add('emailClub')
            ->add('pageFb')
            ->add('pageInsta')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Club::class,
            'current_logo_path' => null,
        ]);
        $resolver->setAllowedTypes('current_logo_path', ['string', 'null']);

    }
}

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use App\Entity\DossierStage;
use App\Entity\Offrestage;
use App\Form\DossierStageType;
use App\Entity\Club;
use App\Entity\Evenement;
use App\Entity\ParticipationEvenement;
use App\Repository\DossierStageRepository;
use App\Repository\EntretienRepository;
use App\Repository\OffreStageRepository;
use App\Repository\UtilisateurRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ClubRepository;
use App\Repository\EvenementRepository;

use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\HttpFoundation\Request;

use App\Service\RevAiService;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Entity\Reclamation;
use App\Form\ReclamationType;
use App\Repository\ReclamationRepository;
use App\Repository\ReponseRecRepository;
use App\Entity\Utilisateur;
use App\Repository\ParticipationEvenementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Dompdf\Dompdf;
use Dompdf\Options;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;
use Symfony\Component\Security\Core\Security;


class AccueilController extends AbstractController
{
    #[Route('/front', name: 'app_front')]
    public function indexe(Security $security, Request $request, EntityManagerInterface $entityManager, UtilisateurRepository $UtilisateurRepository): Response
    {
        $u = $security->getUser();
        if (!$u) {
            return $this->redirectToRoute('app_login');
        }
        $currentDate = new \DateTime();
        $user = $UtilisateurRepository->findOneBy(['id' => 58]);
        $reclamation = new Reclamation();
        $reclamation->setEtat("non traité");
        $reclamation->setIdUser($user);
        $reclamation->setDate($currentDate);
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reclamation);
            $entityManager->flush();
            pnotify()->addSuccess('Your complaint has been addded successfully !.');
            return $this->redirectToRoute('app_front', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('basefront.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form,
            'user' => $u,
        ]);
    }
    #[Route('/acceuil', name: 'app_app')]
    public function acceuil(): Response
    {
        return $this->render('Front/index.html.twig', [
            'controller_name' => 'AccueilController',
        ]);
    }

    #[Route('/internships', name: 'app_internships')]
    public function internships(OffrestageRepository $offrestageRepository, DossierStageRepository   $dossierStageRepository, PaginatorInterface $paginatorInterface, Request $req): Response
    {
        $dossier = $dossierStageRepository->findDossiersByUserIdWithOffreStage(55);
        $dossier = $paginatorInterface->paginate(
            $dossier, /* query NOT result */
            $req->query->getInt('page', 1),
            1
        );
        $offrestage =  $offrestageRepository->findAll();
        $offrestage = $paginatorInterface->paginate(
            $offrestage, /* query NOT result */
            $req->query->getInt('page', 1),
            3
        );
        return $this->render('accueil/internships.html.twig', [
            'offreStage' => $offrestage,
            'dossier' => $dossier,
        ]);
    }
    #[Route('/internship-details/{id}', name: 'app_internship-details')]
    public function internship_details($id, OffrestageRepository $offrestageRepository): Response
    {

        return $this->render('accueil/internship-details.html.twig', [
            'offreStage' => $offrestageRepository->find($id),

        ]);
    }
    #[Route('/apply/{id}', name: 'app_apply')]
    public function apply($id, Security $security, OffrestageRepository $offrestageRepository, ManagerRegistry $manager, Request $req, UtilisateurRepository $utilisateurRepository): Response
    {
        $u = $security->getUser();
        if (!$u) {
            return $this->redirectToRoute('app_login');
        }
        $em = $manager->getManager();
        $dossier = new DossierStage();
        $dossier->setIdUser($utilisateurRepository->find($u->getUserIdentifier()));
        $dossier->setIdOffre($offrestageRepository->find($id));
        $form = $this->createForm(DossierStageType::class, $dossier);

        $form->handleRequest($req);

        if ($form->isSubmitted()) {
            // Handle file uploads
            $cvFile = $form['cv']->getData();
            $conventionFile = $form['convention']->getData();
            $copieCinFile = $form['copie_cin']->getData();

            // Define the uploads directory
            $uploadsDirectory = $this->getParameter('uploads_directory');
            // Upload CV file
            $cvFileName = md5(uniqid()) . '.' . $cvFile->guessExtension();
            $cvFile->move($uploadsDirectory, $cvFileName);
            $dossier->setCv($cvFileName);
            // Upload convention file
            $conventionFileName = md5(uniqid()) . '.' . $conventionFile->guessExtension();
            $conventionFile->move($uploadsDirectory, $conventionFileName);
            $dossier->setConvention($conventionFileName);
            // Upload copie cin file
            $copieCinFileName = md5(uniqid()) . '.' . $copieCinFile->guessExtension();
            $copieCinFile->move($uploadsDirectory, $copieCinFileName);
            $dossier->setCopieCin($copieCinFileName);
            // Persist the DossierStage object
            $em->persist($dossier);
            $em->flush();

            // Redirect to the homepage or any other route
            return $this->redirectToRoute('app_front');
        }

        return $this->render("accueil/apply.html.twig", [
            'offreStage' => $offrestageRepository->find($id),
            'form' => $form->createView(),
        ]);
    }

    #[Route('/callendar', name: 'app_accueil')]
    public function callendar(): Response
    {
        return $this->render('accueil/upcoming-interview.html.twig', [
            'controller_name' => 'AccueilController',
        ]);
    }

    #[Route('/speech-recognition', name: 'speech_recognition')]
    public function speechRecognition(Request $request, RevAiService $revAiService): JsonResponse
    {
        // Handle file upload
        $audioFile = $request->files->get('audio_file');

        if (!$audioFile instanceof UploadedFile) {
            // Return error response
            return new JsonResponse(['error' => 'No audio file uploaded'], Response::HTTP_BAD_REQUEST);
        }

        // Process speech recognition
        try {
            $partialTranscription = $revAiService->transcribePartialAudio($audioFile);
            $finalTranscription = $revAiService->transcribeFinalAudio($audioFile);

            // Return response with partial and final transcriptions
            return new JsonResponse([
                'partial_transcription' => $partialTranscription,
                'final_transcription' => $finalTranscription,
            ]);
        } catch (\Exception $e) {
            // Return error response
            return new JsonResponse(['error' => 'Speech recognition failed: ' . $e->getMessage()], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }
    #[Route('/speechi', name: 'app_accueil_user')]
    public function speechi(): Response
    {
        return $this->render('accueil/ai.html.twig', [
            'controller_name' => 'AccueilController',
        ]);
    }

    #[Route('/upcoming', name: 'app_upcoming')]
    public function upcomingInterviews(Security $security, EntretienRepository $entretienRepository, PaginatorInterface $paginatorInterface, Request $req): Response
    {
        $u = $security->getUser();
        if (!$u) {
            return $this->redirectToRoute('app_login');
        }
        $currentDate = new \DateTime();
        // wa9t twali fama session bch nbdl l 55 bl IDUSER ELI CONNECTE
        $interviews = $entretienRepository->findInterviewsByIdUserAndDateGreaterThan($u->getUserIdentifier(), $currentDate);
        $interviews = $paginatorInterface->paginate(
            $interviews, /* query NOT result */
            $req->query->getInt('page', 1),
            1
        );
        return $this->render('accueil/upcoming.html.twig', [
            'controller_name' => 'AccueilController',
            'interviews' => $interviews,
        ]);
    }
    #[Route('/myinternships', name: 'app_myinternships')]
    public function myinternships(Security $security, DossierStageRepository $dossierStageRepository, PaginatorInterface $paginatorInterface, Request $req, OffrestageRepository $offrestageRepository): Response
    {
        $u = $security->getUser();
        if (!$u) {
            return $this->redirectToRoute('app_login');
        }
        $offrestage =  $offrestageRepository->findAll();
        $offrestage = $paginatorInterface->paginate(
            $offrestage, /* query NOT result */
            $req->query->getInt('page', 1),
            1
        );
        $dossier = $dossierStageRepository->findDossiersByUserIdWithOffreStage($u->getUserIdentifier());
        $dossier = $paginatorInterface->paginate(
            $dossier, /* query NOT result */
            $req->query->getInt('page', 1),
            1
        );
        return $this->render('accueil/myinternships.html.twig', [
            'controller_name' => 'AccueilController',
            'dossier' => $dossier,
            'offreStage' => $offrestage,
        ]);
    }

    #[Route('/accueil', name: 'app_accueil')]

templates/accueil/club/evenements.html.twig
{% extends 'basefront.html.twig' %}

{% block title %}Evenements!{% endblock %}
 {% block header %}
     <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="{{path('app_front')}}" class="logo">
                            Espritify
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><a href="{{path('app_front')}}" class="active">Home</a></li>
                            <li class="scroll-to-section"><a href="{{path('app_quizz')}}">Quizz</a></li>
                            <li class="has-sub">
                                <a href="javascript:void(0)">Other Quizzes</a>
                                <ul class="sub-menu">
                                    <li><a class="dropdown-item"
                                            href="{{ path('app_other_quizzes', {'category': 9}) }}">General
                                            Knowledge</a></li>
                                    <li><a class="dropdown-item"
                                            href="{{ path('app_other_quizzes', {'category': 10}) }}">Books</a></li>
                                    <li><a class="dropdown-item"
                                            href="{{ path('app_other_quizzes', {'category': 21}) }}">Sport</a></li>
                                    <li><a class="dropdown-item"
                                            href="{{ path('app_other_quizzes', {'category': 25}) }}">Art</a></li>
                                    <li><a class="dropdown-item"
                                            href="{{ path('app_other_quizzes', {'category': 30}) }}">Science:Gadgets</a>
                                    </li>
                                    <li><a class="dropdown-item"
                                            href="{{ path('app_other_quizzes', {'category': 18}) }}">Science:Computers</a>
                                    </li>
                                    <li><a class="dropdown-item"
                                            href="{{ path('app_other_quizzes', {'category': 32}) }}">Cartoon</a></li>
                                </ul>
                            </li>
                            <li class="scroll-to-section"><a href="{{path('app_cours')}}">Courses</a></li>
                            <li class="scroll-to-section"><a data-toggle="modal" data-target="#myModal">Voice
                                    Assistant</a></li>
                            <li class="has-sub">
                                <a href="javascript:void(0)" href="#top">Internships</a>
                                <ul class="sub-menu">
                                    <li><a href="{{path('app_internships')}}">Available Internships</a></li>
                                    <li><a href="{{path('app_upcoming')}}">MY Interviews</a></li>
                                    <li><a href="{{path('app_myinternships')}}">MY Internships</a></li>
                                </ul>
                            </li>
                            <li><a href="{{path('app_conversation_index')}}">Live Chat</a></li>

                            <li class="has-sub">
                                <a href="{{path('app_club_details')}}">Clubs</a>
                                <ul class="sub-menu">
                                    <li><a href="{{path('calendar')}}">Calendrier des évènements</a></li>
                                    <li><a href="{{path('catalogue')}}">Catalogue</a></li>
                                    <li><a href="{{path('mes_participations')}}">Mes participations</a></li>

                                </ul>
                            </li>


                            <li class="scroll-to-section"><a href="#contact">Contact Us</a></li>
                            <li>
                                <a href="{{ path('app_notifs') }}">
                                    <i class="fas fa-bell"></i> <!-- FontAwesome bell icon -->
                                </a>
                            </li>
                            <li class="scroll-to-section"><a href="#apply"><i class="fa-solid fa-user"></i></a></li>
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>

 {% endblock %}
{% block banner %}
{% endblock %}
    {% block body %}

        <section class="heading-page header-text" id="top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <h6>Here are our upcoming meetings</h6>
                        <h2>Upcoming Meetings</h2>
                    </div>
                </div>
            </div>
        </section>

        <section class="meetings-page" id="meetings">
        <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="filters">
                            <ul>
                                <li data-filter="*"  class="active">All Meetings</li>
                                <li data-filter=".soon">Soon</li>
                                <li data-filter=".imp">Important</li>
                                <li data-filter=".att">Attractive</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-12">

                        <div class="row grid">
                            {% for evenement in evenements %}
                                <div class="col-lg-4 templatemo-item-col all soon">
                                    <div class="meeting-item">

                                        <div class="thumb">
                                            <a href="{{path('app_evenements_details', {'id': club.id})}}"><img src="{{ asset('/uploads/brochures/' ~ club.logo)}}" height="200" width="100"alt=""></a>
                                        </div>
                                        <div class="down-content">
                                            <div class="price">
                                                <img src="{{ asset("assets/img/logos/icons8-ruban.png")}}" style="height: 30px; width: 30px; vertical-align: middle;"><span>{{ evenement.idClub }}</span>
                                            </div>
                                            <div class="price">
                                                <img src="{{ asset("assets/img/logos/icons8-ruban.png")}}" style="height: 30px; width: 30px; vertical-align: middle;"><span>{{ evenement.titre }}</span>
                                            </div>
                                            <div class="date">
                                                <h5> <img src="{{ asset("assets/img/logos/icons8-ruban3.png")}}" style="height: 30px; width: 30px; vertical-align: middle;"> {{ evenement.dateDebut|date }} <span>TO</span></h5>
                                                <h5>{{ evenement.dateFin|date }} <span></span></h5>

                                            </div>
                                            <div></div>
                                            <a href="{{path('app_meeting-details')}}"><h4><img src="{{ asset("assets/img/logos/icons8-ruban2.png")}}" style="height: 30px; width: 30px; vertical-align: middle;">{{ evenement.lieu }}</h4></a>
                                         <img src="{{ asset("assets/img/logos/icons8-book-32.png")}}" style="height: 30px; width: 30px; vertical-align: middle;"><span>{{ evenement.description }}</span>
                                            <div></br></div>
                                            <a href="{{path('app_evenements_details', {'id': club.id})}}" class="filters" style="horizental-align: right;">

                                                <form action="{{ path('participer_evenement', {'id': evenement.id}) }}" method="post">
                                                    <ul>
                                                        <li data-filter="*"  class="active">  <button   class="main-button-red" type="submit">Participer</button>
                                                        </li>
                                                    </ul>
                                                </form>

                                            </a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}




                        </div>
                        <div class="col-lg-12">
                            <div class="pagination">
                                <ul>
                                    <li><a href="#">1</a></li>
                                    <li class="active"><a href="#">2</a></li>
                                    <li><a href="#">3</a></li>
                                    <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <style>
            .main-button-red {
                font-size: 13px;
                color: #fff;
                background-color: #a12c2f;
                padding: 11px 30px;
                display: inline-block;
                border-radius: 22px;
                font-weight: 600;
                text-transform: uppercase;
                transition: all .3s;
                cursor: pointer;
                margin: 0px 3px;
                border: none;
                outline: none;
            }

            .main-button-red:hover {
                background-color: #fff;
                color: #a12c2f;
            }
        </style>

    {% endblock %}

templates/accueil/club/weekly_catalogue.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weekly Events Catalog</title>
    <style>
        body {
            font-family: Roboto;
            padding: 20px;
        }
        .event {
            margin-bottom: 20px;
            border-bottom: 1px solid #a12c2f;
            padding-bottom: 10px;
        }
        .event-title {
            font-size: 20px;
            font-weight: bold;
            color: #a12c2f;
            margin-bottom: 5px;
        }
        .event-club {
            color: #666;
            margin-bottom: 5px;
        }
        .event-description {
            color: #777;
        }
        .event-start {
            color: #a12c2f;
        }
    </style>
</head>
<body>
<h1 class="event-start">Weekly Events Catalog</h1>
{% for event in events %}
        <div class="event">
            <div class="event-title">{{ event.titre }}</div>
            <div class="event-description">{{ event.description }}</div>
            <div class="event-club">Club: {{ event.idClub }}</div>

            <div class="event-start">Start Date: {{ event.dateDebut|date("Y-m-d H:i:s") }}</div>
            <div class="event-start">End Date: {{ event.dateFin|date("Y-m-d H:i:s") }}</div>

        </div>
{% endfor %}
</body>
</html>